server:
  port: 1206

spring:
  application: 
    name: tech-trekker
  
  # security:
  #   user:
  #     name: "Tapas"
  #     password: "Bindas"


  datasource:
    url: "jdbc:mysql://localhost/blog"
    username: "root"
    password: "Bindasc00l"

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true

    properties:
      hibernate:
        format_sql: true

upload:
  file:
    profile: "profile-images"
    blog: 
      banner: "blog-banner-images"

      

